### ISSUE TITLE
Please take down unaffiliated logos

### ISSUE THREAD

**Issue by pspacek** [ipviolations/ipv4flagday#1]
Hello,

the current version of web https://ipv4flagday.net/ contains CZ.NIC (and other logos) of companies which in fact did not have anything to do with the event, and did not approve usage of their logo there.

Even though I appreciate the sarcasm I have to formally request you remove logos from the web ASAP.

Thank you for understanding.
Petr Špaček  @  CZ.NIC

**Comment by ipviolations** [comment]
Looks like our team of researchers and web designers made a mistake. We internally reviewed your case and can confirm that CZ.NIC doesn't love the internet enough to be listed and has therefor been removed in commit c4a6bd9. Please accept apologies on behalf of the whole team, do not send lawyers as we have no place to store them on-site. Thanks!

**Comment by vcunat** [comment]
I can still see two logos on the page.
