### ISSUE TITLE
please change your logo

### ISSUE THREAD

**Issue by Habbie** [ipviolations/ipv4flagday#11]
Your current logo is an unauthorised, edited copy of the DNS Flag Day logo, and you have no permission to use it.

**Comment by ipviolations** [comment]
Thanks for your great contribution to the IPv4flagday project. Your attention is highly appreciated, as you probably have much more important stuff to do than opening issues on Github. Unfortunately our barrista don't have a Github account, but they told me to link you [to this](https://fairuse.stanford.edu/overview/fair-use/what-is-fair-use/). Again, please do not send lawyers as we can not store them on-site.

**Comment by Zenexer** [comment]
@Habbie I’m not a lawyer, but if I’m not mistaken, parodies are partially exempt from IP laws, at least in the US.

Edit: Looks like there’s significant precedent for this. Even if the parody were commercial in nature, it would [probably still be protected, per Campbell v. Acuff-Rose Music, Inc.](https://en.wikipedia.org/wiki/Campbell_v._Acuff-Rose_Music,_Inc.).

**Comment by Habbie** [comment]
> @Habbie I’m not a lawyer, but if I’m not mistaken, parodies are partially exempt from IP laws, at least in the US.

Asking never hurt :)

**Comment by Zenexer** [comment]
@Habbie It doesn’t, but your request came across as rude and ignorant. In particular “unauthorised” and “no permission” are fairly condescending on your part. I believe I’ve confirmed that the work here is protected as a parody, and I edited the conclusion into my previous reply.
