### ISSUE TITLE
Move repository to site that supports IPv6

### ISSUE THREAD

**Issue by nivex** [ipviolations/ipv4flagday#17]
Github has steadfastly refused to enable IPv6 support. This code repository should be moved somewhere that supports it so as not to become unreachable after Flag Day.

**Comment by ipviolations** [comment]
Maybe we should just push github to finally add IPv6 support, so their site doesn't become unreachable after flag day. I suggest you open up a support ticket.

**Comment by nivex** [comment]
I have done so repeatedly over the last 10 years. I have also challenged their representatives at expos. They won't budge. You're welcome to keep trying to move that mountain. I've already started going around it.

**Comment by nivex** [comment]
I'm done with this farce. Closing all my open issues.
