### ISSUE TITLE
Site check failing

### ISSUE THREAD

**Issue by nivex** [ipviolations/ipv4flagday#3]
When I enter my domain (nivex.net) in the box and click Test I receive the error:
> Invalid input or other unexpected error, sorry!

If the current code becomes too difficult to troubleshoot, I recommend using a more established test such as Mythic Beasts: https://www.mythic-beasts.com/ipv6/health-check

**Comment by JackThursby252** [comment]
Same here... Seems like something on the backend broke years ago and no one noticed... Thanks for the link to the other test, works fine with my domain.

**Comment by nivex** [comment]
It never worked. This issue was opened days after the site went live. There have been no repo commits since then.

**Comment by nivex** [comment]
I'm done with this farce. Closing all my open issues.
